spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect